### PR TITLE
Feature/score home screen

### PR DESCRIPTION
**Pull request by tingaloo**
Display Campaign Scores on Home screen

## Description
It fetches the campaign information for EACH individual campaign for its score. (Number of races)
It will load AFTER races are fetched.
Finally AFTER all information is loaded, scores will display.

Note: This change costs 100+ API requests. On the upside, ALL campaign data is loaded upfront.

## Motivation and Context
#169 

## How Has This Been Tested?
Tested locally.

## Screenshots (highly recommended):
screen shot 2016-08-08 at 8 53 40 am

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] I've talked through the changes with a team lead
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mkalish** [comment]
Awesome! This looks great.  I wouldn't worry too much about the inefficiency because the requests will get cached so it should only be slow for the first time the page is loaded

**Comment by tingaloo** [comment]
At first I had setState fire 100+ times, THAT was bad.

Also, I suggest creating more json files with smaller subsets of data. Say a json file that goes like 
`
{"14A1": {Campaign data object},
   "14A2": {Campaign data obj},
...
}
`

Otherwise for issue #135 we need to scan EACH campaign and ALL its contributors then aggregate the results (very inefficient). Instead we can create a json file that looks like this

`{contributorID: [{Campaign1 data obj}, {Campaign2 data obj, ... }], contributorID2: [...], ...}`

 and fetch it once without Promise.all and all that async stuff (too fancy).

It depends on how dynamic the data is (i haven't a clue), since the cost of maintaining/updating the data can be a bit much (it can be automated!). But at least it will save a massive headache on the front-end (much less logic).

What do you think?

**Comment by mkalish** [comment]
So the API is actually querying a database rather than pulling static JSON files.  The goal was to have a UI agnostic API that could be used for other things.  For #135, its going to require a new API in the back end that will query the contributions by contributor and populate the candidate

**Comment by tingaloo** [comment]
Oh ok, i'll talk to you about getting the vagrant env setup later since I had trouble setting up the backend.

**Pull request merged**
