### PR TITLE
edited candidate service to include scorecard scores

### PR DESCRIPTION
**Pull request by jkoul**
@mkalish - I got the scores showing up in the API in a new "campaign.scores" object. They seem to mostly work, but I didn't go over it too carefully. I wasn't able to figure out how to access ward-level candidates to calculate the ward score for those candidates, so hopefully you can help get that to the finish line.

Let me know if you have any questions.

### CODE REVIEW

**Comment by mkalish** [comment]
I can't see the conflicts can you try pulling the latest code and resolving them?

**Comment by jkoul** [comment]
Ok I'll give it a shot.....might not be able to until Thurs or Fri though.

On Tue, Mar 22, 2016 at 7:54 AM, mkalish <notifications@github.com> wrote:

> I can't see the conflicts can you try pulling the latest code and
> resolving them?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/codefordc/dc-campaign-finance-watch/pull/98#issuecomment-199777706>
>



-- 
Jeremy Koulish
jkoulish@gmail.com
917-597-4397
http://kouli.sh

*We are drowning in information, while starving for wisdom. The world
henceforth will be run by synthesizers, people able to put together the
right information at the right time, think critically about it, and make
important choices wisely.*
*-E.O. Wilson*

**Comment by mkalish** [comment]
No problem... it should be an easy switch out from the raw percentages to the scores

**Comment by jkoul** [comment]
Ok let's try this now......

**Pull request merged**
